### ISSUE TITLE
License

### ISSUE THREAD

**Issue by fmueller-inovex** [fgnass/google-calendar-app#4]
Thanks for your app. Can you please [add a license](https://help.github.com/articles/adding-a-license-to-a-repository/) to this repository?

**Comment by fgnass** [comment]
There already is one: https://github.com/fgnass/google-calendar-app/blob/master/UNLICENSE

**Comment by fmueller-inovex** [comment]
@fgnass Sorry about that. I must have been a little blind. I misinterpreted "Unlicense" with "Unlicensed".
